# Generated by Django 4.2.5 on 2023-10-15 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('isbn_no', models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999999999999)])),
                ('author_name', models.CharField(max_length=30)),
                ('genre', models.CharField(max_length=100)),
                ('inventory', models.IntegerField()),
                ('publication_year', models.PositiveIntegerField()),
            ],
        ),
    ]
